name: Test JMeter Action

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v1

      - name: perf Action for Jmeter
        uses: QAInsights/PerfAction@2.0
        
      - name: Run JMeter Action 1 MAVS
        uses: ./
        with:
          testFilePath: Script/S01_SimpleExample.jmx
          outputReportsFolder: reports
          args: "--loglevel INFO"

    - name: Upload Results
      uses: actions/upload-artifact@v2
      with:
      name: jmeter-results
      path: result.jtl